version: '3'
services:
  exam-mariadb:
    image: mariadb:latest
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: exam
      MYSQL_USER: exam
      MYSQL_PASSWORD: exam
      MYSQL_ALLOW_EMPTY_PASSWORD: yes